# Generated by Django 5.0.3 on 2024-04-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_student_age_remove_student_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
